apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: 600519.SH
spec:
  replicas: 1
  template:
    metadata:
      name: 600519.SH
      labels:
        interval: 5
    spec:
      containers:
      - name: quote
        image: quote:v1
        command: [ "quote"]
        args: ["STOCKCODE", "INTERVAL"]
        env:
          - name: STOCKCODE
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: INTERVAL
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['interval']