apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dailyranges.quote.eagle.io
spec:
  group: quote.eagle.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                open:
                  type: number
                high:
                  type: number
                low:
                  type: number
                date:
                  type: string
  scope: Namespaced
  names:
    plural: dailyranges
    singular: dailyrange
    kind: Dailyrange
    shortNames:
    - dr